# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:
/*let
  baseDataset = "vault/sys/atom";
  bootEnvironmentName = "/ROOT/17.03";
  datasets = [ { mountPoint = "/home/john/.local/share/lxc";
                 dataset = "vault/sys/atom/home/john/local/share/lxc"; }
             ];
in
rec {

  fileSystems =
    map ({ mountPoint, dataset ? "${baseDataset}${bootEnvironmentName}${mountPoint}" }:
        { "${mountPoint}" = { device = "${dataset}"; fsType = "zfs"; }; }) datasets;*/
{
  fileSystems."/mnt/lilan/Data" =
    { device = "lilan.ramsden.network:/mnt/tank/data/Atreides";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Downloading/Torrents" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Torrents";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Downloading/Downloads/Complete" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Downloads/Complete";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Downloading/Downloads/Incomplete" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Downloads/Incomplete";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Series/Series" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Series";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Series/Anime" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Anime";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Series/Documentary" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Documentary";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Series/Lectures" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Lectures";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Series/Animated" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Animated";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Series/Podcasts/Video" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Podcasts/Video";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Series/Podcasts/Audio" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Podcasts/Audio";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Movies" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Movies";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };

  fileSystems."/mnt/lilan/media/Music" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Music";
      fsType = "nfs";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "user" ];
    };
}
