# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "vault/sys/atom/ROOT/default";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "vault/sys/atom/ROOT/default/nix";
      fsType = "zfs";
    };

  fileSystems."/nix/store" =
    { device = "vault/sys/atom/ROOT/default/nix/store";
      fsType = "zfs";
    };

  fileSystems."/nix/.rw-store" =
    { device = "vault/sys/atom/ROOT/default/nix/rw-store";
      fsType = "zfs";
    };

  fileSystems."/nix/.ro-store" =
    { device = "vault/sys/atom/ROOT/default/nix/ro-store";
      fsType = "zfs";
    };

  fileSystems."/nix/var" =
    { device = "vault/sys/atom/ROOT/default/nix/var";
      fsType = "zfs";
    };

  fileSystems."/nix/var/nix" =
    { device = "vault/sys/atom/ROOT/default/nix/var/nix";
      fsType = "zfs";
    };

  fileSystems."/nix/var/log" =
    { device = "vault/sys/atom/ROOT/default/nix/var/log";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "vault/sys/atom/ROOT/default/var";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "vault/sys/atom/ROOT/default/var/lib";
      fsType = "zfs";
    };

  fileSystems."/var/cache" =
    { device = "vault/sys/atom/var/cache";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    { device = "vault/sys/atom/var/log";
      fsType = "zfs";
    };

  fileSystems."/var/log/journal" =
    { device = "vault/sys/atom/var/log/journal";
      fsType = "zfs";
    };

  fileSystems."/var/lib/nixos" =
    { device = "vault/sys/atom/ROOT/default/var/lib/nixos";
      fsType = "zfs";
    };

  fileSystems."/var/lib/systemd" =
    { device = "vault/sys/atom/ROOT/default/var/lib/systemd";
      fsType = "zfs";
    };

  fileSystems."/var/lib/containers" =
    { device = "vault/sys/atom/ROOT/default/var/lib/containers";
      fsType = "zfs";
    };

  fileSystems."/var/lib/systemd/coredump" =
    { device = "vault/sys/atom/ROOT/default/var/lib/systemd/coredump";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "vault/sys/atom/home";
      fsType = "zfs";
    };

  fileSystems."/home/john" =
    { device = "vault/sys/atom/home/john";
      fsType = "zfs";
    };

  fileSystems."/home/john/.cache" =
    { device = "vault/sys/atom/home/john/cache";
      fsType = "zfs";
    };

  fileSystems."/home/john/.config" =
    { device = "vault/sys/atom/home/john/config";
      fsType = "zfs";
    };

  fileSystems."/home/john/.local" =
    { device = "vault/sys/atom/home/john/local";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6E67-E683";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/de6bf709-e584-453f-a385-861af726c5bd"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
