# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "vault/sys/atom/ROOT/default";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "vault/sys/atom/ROOT/default/nix";
      fsType = "zfs";
    };

  fileSystems."/nix/store" =
    { device = "vault/sys/atom/ROOT/default/nix/store";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "vault/sys/atom/ROOT/default/var";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "vault/sys/atom/ROOT/default/var/lib";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    { device = "vault/sys/atom/var/log";
      fsType = "zfs";
    };

  fileSystems."/nix/.ro-store" =
    { device = "vault/sys/atom/ROOT/default/nix/ro-store";
      fsType = "zfs";
    };

  fileSystems."/var/log/journal" =
    { device = "vault/sys/atom/var/log/journal";
      fsType = "zfs";
    };

  fileSystems."/var/cache" =
    { device = "vault/sys/atom/var/cache";
      fsType = "zfs";
    };

  fileSystems."/var/lib/systemd" =
    { device = "vault/sys/atom/ROOT/default/var/lib/systemd";
      fsType = "zfs";
    };

  fileSystems."/nix/var" =
    { device = "vault/sys/atom/ROOT/default/nix/var";
      fsType = "zfs";
    };

  fileSystems."/var/lib/nixos" =
    { device = "vault/sys/atom/ROOT/default/var/lib/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "vault/sys/atom/home";
      fsType = "zfs";
    };

  fileSystems."/var/lib/containers" =
    { device = "vault/sys/atom/ROOT/default/var/lib/containers";
      fsType = "zfs";
    };

  fileSystems."/nix/.rw-store" =
    { device = "vault/sys/atom/ROOT/default/nix/rw-store";
      fsType = "zfs";
    };

  fileSystems."/home/john" =
    { device = "vault/sys/atom/home/john";
      fsType = "zfs";
    };

  fileSystems."/var/lib/systemd/coredump" =
    { device = "vault/sys/atom/ROOT/default/var/lib/systemd/coredump";
      fsType = "zfs";
    };

  fileSystems."/nix/var/log" =
    { device = "vault/sys/atom/ROOT/default/nix/var/log";
      fsType = "zfs";
    };

  fileSystems."/nix/var/nix" =
    { device = "vault/sys/atom/ROOT/default/nix/var/nix";
      fsType = "zfs";
    };

  fileSystems."/home/john/.cache" =
    { device = "vault/sys/atom/home/john/cache";
      fsType = "zfs";
    };

  fileSystems."/home/john/.local" =
    { device = "vault/sys/atom/home/john/local";
      fsType = "zfs";
    };

  fileSystems."/home/john/.config" =
    { device = "vault/sys/atom/home/john/config";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6E67-E683";
      fsType = "vfat";
    };

  fileSystems."/tmp" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/home/john/.cache/google-chrome" =
    { device = "tmpfs";
      fsType = "tmpfs";
      options = [ "uid=1000" "gid=100"];
    };

  fileSystems."/home/john/University" =
    { device = "vault/data/University";
      fsType = "zfs";
    };

  fileSystems."/home/john/Books" =
    { device = "vault/data/Books";
      fsType = "zfs";
    };

  fileSystems."/home/john/Computer" =
    { device = "vault/data/Computer";
      fsType = "zfs";
    };

  fileSystems."/home/john/Personal" =
    { device = "vault/data/Personal";
      fsType = "zfs";
    };

  fileSystems."/home/john/Pictures" =
    { device = "vault/data/Pictures";
      fsType = "zfs";
    };

  fileSystems."/home/john/Reference" =
    { device = "vault/data/Reference";
      fsType = "zfs";
    };

  fileSystems."/home/john/Workspace" =
    { device = "vault/data/Workspace";
      fsType = "zfs";
    };

  fileSystems."/mnt/lilan/Data" =
    { device = "lilan.ramsden.network:/mnt/tank/data/Atreides";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Downloading/Torrents" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Torrents";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Downloading/Downloads/Complete" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Downloads/Complete";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Downloading/Downloads/Incomplete" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Downloads/Incomplete";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Series/Series" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Series";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Series/Anime" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Anime";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Series/Documentary" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Documentary";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Series/Lectures" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Lectures";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Series/Animated" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Animated";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Series/Podcasts/Video" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Podcasts/Video";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Series/Podcasts/Audio" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Series/Podcasts/Audio";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Movies" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Movies";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  fileSystems."/mnt/lilan/media/Music" =
    { device = "lilan.ramsden.network:/mnt/tank/media/Music";
      fsType = "nfs4";
      options = [ "noauto" "x-systemd.automount" "x-systemd.device-timeout=175" "timeo=15" "x-systemd.idle-timeout=1min" "users" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/de6bf709-e584-453f-a385-861af726c5bd"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = "powersave";
}
